-- combined.sql
-- Generated by ChatGPT: merged triggers/functions into a single runnable SQL file.
-- Order:
-- 1) uuid extension + revision framework
-- 2) recalc_scam_phone_from_posts(p_phone)
-- 3) post_tel_numbers trigger that calls recalc

BEGIN;

-- ต้องเปิด uuid extension ถ้ายังไม่มี
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

--------------------------------------------------------------------------------
-- 1. ฟังก์ชัน generic สำหรับบันทึก revision
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_generic_revision()
RETURNS trigger AS $$
DECLARE
  v_editor uuid;
  v_rev_table text := TG_TABLE_NAME || '_revisions';
  v_exists bool;
BEGIN
  -- หา editor_id จาก session variable (GUC)
  BEGIN
    v_editor := NULLIF(current_setting('app.editor_id', true), '')::uuid;
  EXCEPTION WHEN others THEN
    v_editor := NULL;
  END;

  -- ตรวจว่าตาราง revision มีจริงไหม
  SELECT EXISTS (
    SELECT 1 FROM information_schema.tables
     WHERE table_name = v_rev_table
  ) INTO v_exists;

  IF NOT v_exists THEN
    RAISE NOTICE 'Revision table % does not exist, skip insert', v_rev_table;
    RETURN NEW;
  END IF;

  -- บันทึก snapshot เก่า (ใช้ BEFORE UPDATE เพื่อเก็บค่า OLD)
  IF TG_OP = 'UPDATE' THEN
    EXECUTE format(
      'INSERT INTO %I (id, %I_id, editor_id, snapshot, created_at)
       VALUES (uuid_generate_v4(), $1, $2, row_to_json($3), now())',
      v_rev_table, TG_TABLE_NAME
    )
    USING OLD.id, v_editor, OLD;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--------------------------------------------------------------------------------
-- 2. ฟังก์ชันสำหรับสร้าง revision table + trigger อัตโนมัติ
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION create_revision_trigger(p_table text)
RETURNS void AS $$
DECLARE
  rev_table text := p_table || '_revisions';
  trg_name text := p_table || '_rev_trg';
BEGIN
  -- 2.1 สร้าง revision table ถ้ายังไม่มี
  EXECUTE format($fmt$
    CREATE TABLE IF NOT EXISTS %I (
      id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
      %I_id uuid REFERENCES %I(id) ON DELETE CASCADE,
      editor_id uuid,
      snapshot jsonb NOT NULL,
      created_at timestamptz DEFAULT now()
    )$fmt$, rev_table, p_table, p_table);

  -- 2.2 ลบ trigger เก่า (ถ้ามี) แล้วสร้างใหม่
  EXECUTE format('DROP TRIGGER IF EXISTS %I ON %I', trg_name, p_table);
  EXECUTE format($fmt$
    CREATE TRIGGER %I
    BEFORE UPDATE ON %I
    FOR EACH ROW
    EXECUTE FUNCTION trg_generic_revision()
  $fmt$, trg_name, p_table);

  RAISE NOTICE '✅ Trigger created for table %', p_table;
END;
$$ LANGUAGE plpgsql;

--------------------------------------------------------------------------------
-- 3. เรียกใช้ครั้งเดียวสำหรับ tables ที่ต้องการ
--------------------------------------------------------------------------------
SELECT create_revision_trigger('posts');
SELECT create_revision_trigger('users');

SELECT create_revision_trigger('post_seller_accounts');
SELECT create_revision_trigger('post_tel_numbers');

SELECT create_revision_trigger('comments');

-- ✅ เพิ่มตารางอื่นได้ในอนาคต
-- SELECT create_revision_trigger('comments');
-- SELECT create_revision_trigger('drivers');
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Scam phone summary recalculation function (must exist before trigger function)
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION recalc_scam_phone_from_posts(p_phone text)
RETURNS void AS $$
DECLARE
  agg_phone text;
  agg_count int;
  agg_last  timestamptz;
  agg_posts uuid[];
  agg_risk  int;
BEGIN
  -- รวมข้อมูลจาก post_tel_numbers ของเบอร์นี้
  SELECT
    tel AS phone,
    COUNT(*)::int AS report_count,
    MAX(created_at) AS last_report_at,
    ARRAY_AGG(DISTINCT post_id)::uuid[] AS post_ids
  INTO
    agg_phone, agg_count, agg_last, agg_posts
  FROM post_tel_numbers
  WHERE tel = p_phone
  GROUP BY tel;

  -- ถ้าไม่มี row ใน post_tel_numbers แล้ว
  IF agg_phone IS NULL THEN
    -- mark ว่า deleted (ยังเก็บ row ไว้เพื่อให้ client sync ลบ)
    UPDATE scam_phones_summary
    SET
      report_count   = 0,
      last_report_at = NULL,
      post_ids       = '{}',
      risk_level     = 0,
      is_deleted     = true,
      updated_at     = now()
    WHERE phone = p_phone;

    -- ถ้าอยากลบ row ทิ้งจริง ๆ ก็ใช้ DELETE แทน UPDATE ด้านบน
    RETURN;
  END IF;

  -- คำนวณ risk จาก count (จะใช้สูตรอะไรก็ได้)
  IF agg_count >= 20 THEN
    agg_risk := 90;
  ELSIF agg_count >= 10 THEN
    agg_risk := 60;
  ELSIF agg_count >= 5 THEN
    agg_risk := 40;
  ELSE
    agg_risk := 10;
  END IF;

  -- upsert summary row
  INSERT INTO scam_phones_summary
    (phone, report_count, last_report_at, post_ids, risk_level, is_deleted, updated_at)
  VALUES
    (agg_phone, agg_count, agg_last, agg_posts, agg_risk, false, now())
  ON CONFLICT (phone) DO UPDATE
  SET
    report_count   = EXCLUDED.report_count,
    last_report_at = EXCLUDED.last_report_at,
    post_ids       = EXCLUDED.post_ids,
    risk_level     = EXCLUDED.risk_level,
    is_deleted     = false,
    updated_at     = now();
END;
$$ LANGUAGE plpgsql;

--------------------------------------------------------------------------------
-- Trigger function + trigger for post_tel_numbers -> scam_phones_summary
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_post_tel_numbers_scam_summary()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM recalc_scam_phone_from_posts(NEW.tel);

  ELSIF TG_OP = 'UPDATE' THEN
    -- ถ้าเบอร์โดนเปลี่ยน: ต้อง recalc ทั้งเบอร์เก่า + เบอร์ใหม่
    IF NEW.tel IS DISTINCT FROM OLD.tel THEN
      PERFORM recalc_scam_phone_from_posts(OLD.tel);
      PERFORM recalc_scam_phone_from_posts(NEW.tel);
    ELSE
      PERFORM recalc_scam_phone_from_posts(NEW.tel);
    END IF;

  ELSIF TG_OP = 'DELETE' THEN
    PERFORM recalc_scam_phone_from_posts(OLD.tel);
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS post_tel_numbers_scam_summary_trg ON post_tel_numbers;

CREATE TRIGGER post_tel_numbers_scam_summary_trg
AFTER INSERT OR UPDATE OR DELETE ON post_tel_numbers
FOR EACH ROW
EXECUTE FUNCTION trg_post_tel_numbers_scam_summary();

COMMIT;
